config/routes.rb
Rails.application.routes.draw do
  get 'visits/new'

  root 'prescriptions#index'
  get 'prescriptions/:id' => 'prescriptions#show', as: :prescription

  get 'prescriptions/:prescription_id/doses' => 'doses#index', as: :doses
  get 'prescriptions/:prescription_id/doses/:id' => 'doses#show', as: :dose
  get 'prescriptions/:prescription_id/add_dose' => 'doses#new', as: :new_dose
  post 'prescriptions/:prescription_id/doses' => 'doses#create'

  get '/sign_in' => 'sessions#patient_or_doctor', as: :overall_sign_in

  get '/patient_sign_in' => 'sessions#newpatient', as: :patient_sign_in
  post '/patient_sign_in' => 'sessions#create_patient'
  delete '/patient_sign_out' => 'sessions#destroy_patient', as: :patient_sign_out

  get '/patient_sign_up' => 'patients#new', as: :patient_sign_up
  post '/patient_sign_up' => 'patients#create', as: :patients

  get '/doctor_sign_in' => 'sessions#newdoctor', as: :doctor_sign_in
  post '/doctor_sign_in' => 'sessions#create_doctor'
  delete '/doctor_sign_out' => 'sessions#destroy_doctor', as: :doctor_sign_out

  get '/doctor_sign_up' => 'doctors#new', as: :doctor_sign_up
  post '/doctor_sign_up' => 'doctors#create', as: :doctors

  get 'doctor/:id/patients' => 'doctors#patients', as: :doctor_view_patients
  get 'doctor/:id/patient/:patient_id' => 'doctors#patient', as: :doctor_view_patient
  get 'doctor/:id/patient/:patient_id/prescription/:prescription_id'=> 'doctors#prescription', as: :doctor_view_prescription
  get 'doctor/:id/patient/:patient_id/new_prescription' => 'doctors#new_prescription', as: :new_prescription
  post 'doctor/:id/patient/:patient_id/prescription' => 'doctors#create_prescription', as: :prescriptions
  get 'doctor/:id/patient_directory' => 'doctors#all_patients', as: :all_patients
  get 'doctor/:id/patient/:patient_id/new_patient_prescription' => 'doctors#new_patient_prescription', as: :new_patient_prescription

end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :patient
  has_many :doses

  def remaining_amount_of_pills
    total_taken = doses.map{|dose| dose.amount_of_pills_taken}.sum
    initial_amount_of_pills - total_taken
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :authenticate_user!

  def index
    if @current_patient
      @prescriptions = Prescription.where patient_id: @current_patient.id

      @old_prescriptions     = @prescriptions.select {|p| p.remaining_amount_of_pills <= 0}
      @current_prescriptions = @prescriptions.select {|p| p.remaining_amount_of_pills > 0}

    elsif @current_doctor
      redirect_to doctor_view_patients_path(id: @current_doctor.id)
    end
  end

  def show
    if @current_patient
      @prescription = @current_patient.prescriptions.find params[:id]
    elsif @current_doctor
      @prescription = @current_doctor.prescriptions.find params[:id]
    end

    @doses = @prescription.doses.order("created_at desc")
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/index.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/titlebarstart' %>Your Prescriptions<%= render 'layouts/titlebarend' %>
<div class="page_content">
  <% if @current_prescriptions.count > 0 %>
    <div class="prescriptions_index">
      <h4>Your Current Prescriptions</h4>
      <div class="prescriptions_index_table">
        <table class="prescriptions_table table table-striped">
          <tr>
            <th>Drug Name</th>
            <th>Doctor</th>
            <th>Initial Amount</th>
            <th>Pills Remaining</th>
            <th>Prescription Length (Days)</th>
          </tr>
          <% @prescriptions.each do |prescription| %>
            <% if prescription.remaining_amount_of_pills > 0 %>
              </tr>
                <td><%= link_to "#{prescription.drug_name}", prescription_path(id: prescription.id)%></td>
                <td><%= prescription.doctor.full_name %></td>
                <td><%= prescription.initial_amount_of_pills %></td>
                <td><%= prescription.remaining_amount_of_pills %></td>
                <td><%= prescription.length_of_prescription %></td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>
  <% if @old_prescriptions.any? %>
    <div class="prescriptions_index">
      <h4>Your Old Prescriptions</h4>
      <div class="prescriptions_index_table">
        <table class="prescriptions_table table table-striped">
          <tr>
            <th>Drug Name</th>
            <th>Doctor</th>
            <th>Initial Amount</th>
            <th>Pills Remaining</th>
            <th>Prescription Length (Days)</th>
          </tr>
          <% @old_prescriptions.each do |prescription| %>
            <tr>
              <td><%= link_to "Old #{prescription.drug_name}", prescription_path(id: prescription.id)%></td>
              <td><%= prescription.doctor.full_name %></td>
              <td><%= prescription.initial_amount_of_pills %></td>
              <td><%= prescription.remaining_amount_of_pills %></td>
              <td><%= prescription.length_of_prescription %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/prescriptions/new.html.erb
<div class="nav_bar">
  <div class="my">
    <h3>my</h3>
  </div>
  <div class="prescription">
    <h3>prescription</h3>
  </div>
  <div class="pal">
    <h3>pal</h3>
  </div>
  <div class="user_nav_bar">
    <% if @current_doctor %>
      <div class="greeting">
        Hello, Dr. <%= @current_doctor.last_name %>
      </div>
      <div class="messages">
        Messages
      </div>
      <div class="sign_out">
        <%= link_to "Sign Out", doctor_sign_out_path, method: :delete %>
      </div>
    <% elsif @current_patient %>
      <div class="greeting">
        Hello, <%= @current_patient.full_name %>
      </div>
      <div class="messages">
        Messages
      </div>
      <div class="sign_out">
      <%= link_to "Sign Out", patient_sign_out_path, method: :delete %>
      </div>
    <% end %>
  </div>
</div>
<div class="title_bar">
  <div class="title_name">
    <h4>Add New Prescription for <%= @patient.full_name %></h4>
  </div>
</div>
<div class="page_content">
  <div class="prescription_greeting">
    <h4>Please enter in your prescription information here</h4>
  </div>
  <div class="prescription_form">
    <%= simple_form_for @prescription do |f| %>
      <%= f.input :drug_name, label: "Drug Name" %>

      <%= f.input :purpose, label: "Purpose" %>

      <%= f.input :instructions, label: "Instructions" %>

      <%= f.input :doses_per_day, label: "Doses Per Day" %>

      <%= f.input :max_dose_amount, label: "Max Dose Amount" %>

      <%= f.input :initial_amount_of_pills, label: "Amount of Pills" %>

      <%= f.input :length_of_prescription, label: "Length of Prescription (Days)" %>

      <%= f.submit "Create New Prescription" %>
    <% end %>
  </div>
</div>

app/views/prescriptions/show.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/titlebarstart' %>
  Your
  <% if @prescription.remaining_amount_of_pills == 0 %>
    Old
  <% end %>
  <%= @prescription.drug_name %>
  Prescription
<%= render 'layouts/titlebarend' %>
<div class="page_content">
  <% if @prescription.remaining_amount_of_pills > 0 %>
    <div class="new_dose btn btn-default">
      <%= link_to 'Add New Dose', new_dose_path(prescription_id: @prescription.id) %>
    </div>
  <% end %>
  <% if @prescription.remaining_amount_of_pills <= 10 %>
    <div class="low_warning">
      Warning: You only have <%= @prescription.remaining_amount_of_pills %> pills left.  If you have not already, please make an appointment with Dr. <%= @prescription.doctor.last_name %> if you will need more medication.
    </div>
  <% end %>
  <%= render 'doses/druginfo' %>
  <%= render 'doses/dosesinfo' %>
  <%= render 'doses/reports' %>
</div>