config/routes.rb
Rails.application.routes.draw do
  get 'visits/new'

  root 'prescriptions#index'
  get 'prescriptions/:id' => 'prescriptions#show', as: :prescription

  get 'prescriptions/:prescription_id/doses' => 'doses#index', as: :doses
  get 'prescriptions/:prescription_id/doses/:id' => 'doses#show', as: :dose
  get 'prescriptions/:prescription_id/add_dose' => 'doses#new', as: :new_dose
  post 'prescriptions/:prescription_id/doses' => 'doses#create'

  get '/sign_in' => 'sessions#patient_or_doctor', as: :overall_sign_in

  get '/patient_sign_in' => 'sessions#newpatient', as: :patient_sign_in
  post '/patient_sign_in' => 'sessions#create_patient'
  delete '/patient_sign_out' => 'sessions#destroy_patient', as: :patient_sign_out

  get '/patient_sign_up' => 'patients#new', as: :patient_sign_up
  post '/patient_sign_up' => 'patients#create', as: :patients

  get '/doctor_sign_in' => 'sessions#newdoctor', as: :doctor_sign_in
  post '/doctor_sign_in' => 'sessions#create_doctor'
  delete '/doctor_sign_out' => 'sessions#destroy_doctor', as: :doctor_sign_out

  get '/doctor_sign_up' => 'doctors#new', as: :doctor_sign_up
  post '/doctor_sign_up' => 'doctors#create', as: :doctors

  get 'doctor/:id/patients' => 'doctors#patients', as: :doctor_view_patients
  get 'doctor/:id/patient/:patient_id' => 'doctors#patient', as: :doctor_view_patient
  get 'doctor/:id/patient/:patient_id/prescription/:prescription_id'=> 'doctors#prescription', as: :doctor_view_prescription
  get 'doctor/:id/patient/:patient_id/new_prescription' => 'doctors#new_prescription', as: :new_prescription
  post 'doctor/:id/patient/:patient_id/prescription' => 'doctors#create_prescription', as: :prescriptions
  get 'doctor/:id/patient_directory' => 'doctors#all_patients', as: :all_patients
  get 'doctor/:id/patient/:patient_id/new_patient_prescription' => 'doctors#new_patient_prescription', as: :new_patient_prescription

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_secure_password
  has_many :prescriptions
  has_many :patients, through: :prescriptions
  has_many :visits

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      session[:doctor_id] = @doctor.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def patients
    @patients = @current_doctor.patients
  end

  def patient
    @patient = @current_doctor.patients.find params[:patient_id]
    @prescriptions = @patient.prescriptions
  end

  def prescription
    @patient = @current_doctor.patients.find params[:patient_id]
    @prescription = @patient.prescriptions.find params[:prescription_id]
    @doses = @prescription.doses.order("created_at desc")
  end

  def new_prescription
    @patient = @current_doctor.patients.find params[:patient_id]
    @prescription = Prescription.new
  end

  def create_prescription
    @patient = Patient.find params[:patient_id]
    @prescription = Prescription.new(prescription_params)
    if @prescription.save
      @patient.prescriptions << @prescription
      @current_doctor.prescriptions << @prescription
      redirect_to doctor_view_patient_path(id: @current_doctor.id, patient_id: @patient.id)
    else
      render :new_prescription
    end
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :email, :password, :password_confirmation, :speciality)
  end

  def prescription_params
    params.require(:prescription).permit(:initial_amount_of_pills, :length_of_prescription, :max_dose_amount, :purpose, :instructions, :doses_per_day, :drug_name)
  end

  def all_patients
    @patients = Patient.all.order("email asc")
  end

  def new_patient_prescription
    @patient = Patient.find params[:patient_id]
    @prescription = Prescription.new
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/all_patients.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/titlebarstart' %>Patients Index<%= render 'layouts/titlebarend' %>
<div class="page_content">
  <table class="patients_table table table-striped">
    <tr>
      <th>Username</th>
      <th>Full Name</th>
    </tr>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to "#{patient.email}", new_patient_prescription_path(id: @current_doctor.id, patient_id: patient.id) %></td>
        <td><%= patient.full_name %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/doctors/edit.html.erb
<h1>Doctors#edit</h1>
<p>Find me in app/views/doctors/edit.html.erb</p>

app/views/doctors/new.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/titlebarstart' %>Doctor Sign Up<%= render 'layouts/titlebarend' %>

<div class="page_content">
  <div class="sign_up_form">
    <%= simple_form_for @doctor do |d| %>
      <%= d.input :first_name, label: false, placeholder: 'First Name' %>

      <%= d.input :last_name, label: false, placeholder: 'Last Name' %>

      <%= d.input :specialty, label: false, placeholder: 'Specialty' %>

      <%= d.input :email, label: false, placeholder: 'Email' %>

      <%= d.input :password, label: false, placeholder: 'Password' %>

      <%= d.input :password_confirmation, label: false, placeholder: 'Password Confirmation' %>

      <%= d.submit "Sign Up" %>
    <% end %>
  </div>
</div>

app/views/doctors/new_patient_prescription.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/titlebarstart' %>Add New Prescription for <%= @patient.full_name %><%= render 'layouts/titlebarend' %>
<div class="page_content">
  <div class="prescription_greeting">
    <h4>Please enter in your prescription information here</h4>
  </div>
  <div class="prescription_form">
    <%= simple_form_for @prescription do |f| %>
      <%= f.input :drug_name, label: "Drug Name" %>

      <%= f.input :purpose, label: "Purpose" %>

      <%= f.input :instructions, label: "Instructions" %>

      <%= f.input :doses_per_day, label: "Doses Per Day" %>

      <%= f.input :max_dose_amount, label: "Max Dose Amount" %>

      <%= f.input :initial_amount_of_pills, label: "Amount of Pills" %>

      <%= f.input :length_of_prescription, label: "Length of Prescription (Days)" %>

      <%= f.submit "Create New Prescription" %>
    <% end %>
  </div>
</div>

app/views/doctors/new_prescription.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/titlebarstart' %>Add New Prescription for <%= @patient.full_name %><%= render 'layouts/titlebarend' %>
<div class="page_content">
  <div class="prescription_form">
      <%= simple_form_for @prescription do |f| %>
        <%= f.input :drug_name, label: false, placeholder: "Drug Name", input_html: {class: "new_prescription_form top_form"} %>

        <%= f.input :purpose, label: false, placeholder: "Purpose", input_html: {class: "new_prescription_form"} %>

        <%= f.input :instructions, label: false, placeholder: "Instructions", input_html: {class: "new_prescription_form"} %>

        <%= f.input :doses_per_day, label: false, placeholder: "Doses Per Day", input_html: {class: "new_prescription_form"} %>

        <%= f.input :max_dose_amount, label: false, placeholder: "Max Dose Amount", input_html: {class: "new_prescription_form"} %>

        <%= f.input :initial_amount_of_pills, label: false, placeholder: "Amount of Pills", input_html: {class: "new_prescription_form"} %>

        <%= f.input :length_of_prescription, label: false, placeholder: "Length of Prescription (Days)", input_html: {class: "new_prescription_form"} %>

        <button class="btn btn-rounded">Create New Prescription</button>
      <% end %>
  </div>
</div>

app/views/doctors/patient.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/titlebarstart' %>Your Prescriptions for <%= @patient.full_name %><%= render 'layouts/titlebarend' %>
<div class="page_content">
  <div class="new_prescription btn btn-default">
    <%= link_to 'Add New Prescription', new_prescription_path(patient_id: @patient.id) %>
  </div>
  <table class="patients_table table table-striped">
    <tr>
      <th>Drug Name</th>
      <th>Initial Amount</th>
      <th>Pills Remaining</th>
      <th>Prescription Length (Days)</th>
    </tr>
    <% @prescriptions.each do |prescription| %>
      <tr>
        <td>
          <% if prescription.doctor_id = @current_doctor.id %>
            <%= link_to "#{prescription.drug_name}", doctor_view_prescription_path(prescription_id: prescription.id)%>
          <% end %>
        </td>
        <td><%= prescription.initial_amount_of_pills %></td>
        <td><%= prescription.remaining_amount_of_pills %></td>
        <td><%= prescription.length_of_prescription %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/doctors/patients.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/titlebarstart' %>Your Patients<%= render 'layouts/titlebarend' %>
<div class="page_content">
  <div class="new_patient btn btn-default">
    <%= link_to 'Add New Patient', all_patients_path %>
  </div>
  <table class="table table-striped">
    <tr>
      <th>Username</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Prescriptions</th>
    </tr>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to "#{patient.email}", doctor_view_patient_path(patient_id: patient.id) %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.prescriptions.count %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/doctors/prescription.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/titlebarstart' %>Your <%= @prescription.drug_name %> Prescription for <%= @patient.full_name %><%= render 'layouts/titlebarend' %>
<div class="page_content">
  <%= render 'doses/druginfo' %>
  <%= render 'doses/dosesinfo' %>
  <%= render 'doses/reports' %>
</div>